name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: alpine:latest
            preinstall: apk add bash coreutils curl git
          - container: centos:latest
            preinstall: dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos && dnf -y install git
          - container: ubuntu:latest
            preinstall: apt-get -y update && apt-get -y install curl git

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Preinstall
        run: ${{ matrix.preinstall }}

      - name: Prepare .tool-versions
        run: echo 'helm latest' > .tool-versions

      - name: asdf install
        uses: asdf-vm/actions/install@v1

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: helm diff version

  macos:
    runs-on: macos-latest

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: helm diff version
